  deploy-mainnet:
    runs-on: ubuntu-latest
    needs: [build-test, garage-checks, opa-policy]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy Settlement contract to Mainnet
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          PAYMENT_TOKEN: ${{ secrets.PAYMENT_TOKEN }}
        run: |
          npx hardhat run scripts/deploySettlement.js --network mainnet
